apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169897195
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169897195
    app.kubernetes.io/part-of: test-app-169897195
  name: java-quarkus-169897195
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169897195
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169897195
    spec:
      containers:
      - image: quay.io/hacdev/cp2yerzb-tenant/test-app-169897195/java-quarkus-169897195@sha256:5db02173c99ec06cfb81ceb3a5abac5e1c6ce56187a39c1fc49d125d5d58353b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
